### PR TITLE
Chore: Update Dependencies November 2024, Release 24.11.0

### PR DESCRIPTION
**Pull request by samuel-esp**
## Motivation

Updating Dependencies November 2024

## Changes

  • Updating virtualenv (20.27.0 -> 20.27.1)
  • Updating mypy (1.12.1 -> 1.13.0)

## Tests done

Unit Tests

## TODO

- [x] I've assigned myself to this PR

### CODE REVIEW

**Comment by samuel-esp** [comment]
Before merging it would be good to also align New Pykube (caas-team/new-pykube#28). I'll add another commit with the New Pykube dependency when the PR is merged

**Comment by samuel-esp** [comment]
Added as mentioned

  •  packaging (24.1 -> 24.2)
  •  new-pykube (24.10.0 -> 24.11.0)

**Comment by samuel-esp** [comment]
Incremented appVersion and chartVersion in order to release the November Update

**Review by JTaeuber — APPROVED** [review]
LGTM

**Pull request merged**
