### PR TITLE
fix: stop upscale while excluded when original replicas set

### PR DESCRIPTION
**Pull request by jonathan-mayer**
## Motivation

Currently if a namespace is excluded but a workload in it has the downscaler/original-replicas annotation the downscaler will scale up the workload. This changes this, so that excluding the namespace or workload will make the downscaler ignore it fully.

I will wait for a response from @samuel-esp to see what he thinks about this change.

## TODO

- [x] I've assigned myself to this PR

### CODE REVIEW

**Comment by samuel-esp** [comment]
Hi @jonathan-mayer, for sure an improvement! Didn't notice this behavior before, thank you for addressing! Can you try add/refactor test to reflect the new logic?

**Review by JTaeuber — APPROVED** [review]
LGTM

**Comment by samuel-esp** [comment]
One use case that could have been lost:

- User includes namespace A, B, C as a target
- User understands that namespace A is not needed anymore, so it deletes it from the target 

In this case resources scaled down in namespace A won't be scaled up again. I'll try to test this scenario on Saturday. If this is confirmed I will address the problem in this way

- Introduce a new argument **--do-not-wake-up-if-not-in-target **
- Refactor the logic with a conditional, but I'll keep the default as it was to avoid compatibili problems 

@jonathan-mayer would it be ok for you?

**Comment by jonathan-mayer** [comment]
Seems like a good idea. Although, I would change the name of the new cli argument to something like `--upscale-excluded-namespaces`.

**Comment by samuel-esp** [comment]
@jonathan-mayer even better because it's shorter name, thank you! We'll make this argument default inside the chart. If the user wants the new behavior, it should set a boolean variable to false inside `values.yaml` (if false, this argument won't be included inside the downscaler deployment)

**Pull request merged**
